export const BOOK_GENRES = [
  'Fiction',
  'Non-Fiction',
  'Mystery',
  'Science Fiction',
  'Fantasy',
  'Romance',
  'Thriller',
  'Horror',
  'Historical Fiction',
  'Biography',
  'Self-Help',
  'Poetry',
  'Drama',
  'Adventure',
  'Children\'s',
  'Young Adult',
  'Science',
  'Technology',
  'Business',
  'Philosophy',
  'Religion',
  'Art',
  'Travel',
  'Cooking',
  'Other'
]; 